version: '3'
services:
    database:
        image: mysql:5.7
        ports: [3306:3306]
        environment:
            MYSQL_ROOT_PASSWORD: rt_psswrd
            MYSQL_DATABASE: hostaway
            MYSQL_USER: sr
            MYSQL_PASSWORD: psswrd